import Foundation

enum AccessibilityIDs {
    enum Settings {
        static let authStatus = "recappi.settings.authStatus"
        static let authStatusText = "recappi.settings.authStatusText"
        static let cloudToggle = "recappi.settings.cloudToggle"
        static let autoPromptToggle = "recappi.settings.autoPromptToggle"
        static let signInGoogleButton = "recappi.settings.signInGoogleButton"
        static let signInGitHubButton = "recappi.settings.signInGitHubButton"
        static let accountActionsMenu = "recappi.settings.accountActionsMenu"
        static let reconnectButton = "recappi.settings.reconnectButton"
        static let signOutButton = "recappi.settings.signOutButton"
        static let openCloudButton = "recappi.settings.openCloudButton"
        static let billingUsage = "recappi.settings.billingUsage"
        static let billingRefreshButton = "recappi.settings.billingRefreshButton"
        static let permissionMicrophoneStatus = "recappi.settings.permissionMicrophoneStatus"
        static let permissionScreenCaptureStatus = "recappi.settings.permissionScreenCaptureStatus"
        static let requestMicrophoneButton = "recappi.settings.requestMicrophoneButton"
        static let requestScreenCaptureButton = "recappi.settings.requestScreenCaptureButton"
        static let refreshPermissionsButton = "recappi.settings.refreshPermissionsButton"
    }

    enum Panel {
        static let audioSourcePicker = "recappi.panel.audioSourcePicker"
        static let recordButton = "recappi.panel.recordButton"
        static let stopButton = "recappi.panel.stopButton"
        static let closeButton = "recappi.panel.closeButton"
        static let discardButton = "recappi.panel.discardButton"
        static let waveformToggle = "recappi.panel.waveformToggle"
        static let recordingSuggestion = "recappi.panel.recordingSuggestion"
        static let meetingPrompt = "recappi.panel.meetingPrompt"
        static let processingTitle = "recappi.panel.processingTitle"
        static let processingDetail = "recappi.panel.processingDetail"
        static let doneTitle = "recappi.panel.doneTitle"
        static let errorTitle = "recappi.panel.errorTitle"
        static let retryButton = "recappi.panel.retryButton"
        static let settingsButton = "recappi.panel.settingsButton"
        static let cloudButton = "recappi.panel.cloudButton"
        static let showButton = "recappi.panel.showButton"
    }

    enum Cloud {
        static let window = "recappi.cloud.window"
        static let authStatus = "recappi.cloud.authStatus"
        static let refreshButton = "recappi.cloud.refreshButton"
        static let billingStatus = "recappi.cloud.billingStatus"
        static let billingButton = "recappi.cloud.billingButton"
        static let plansButton = "recappi.cloud.plansButton"
        static let signInGoogleButton = "recappi.cloud.signInGoogleButton"
        static let signInGitHubButton = "recappi.cloud.signInGitHubButton"
        static let reconnectButton = "recappi.cloud.reconnectButton"
        static let recordingsList = "recappi.cloud.recordingsList"
        static let recordingRowPrefix = "recappi.cloud.recordingRow."
        static let loadMoreButton = "recappi.cloud.loadMoreButton"
        static let summaryText = "recappi.cloud.summaryText"
        static let actionItemsText = "recappi.cloud.actionItemsText"
        static let transcriptText = "recappi.cloud.transcriptText"
        static let latestJobStatus = "recappi.cloud.latestJobStatus"
        static let loadTranscriptButton = "recappi.cloud.loadTranscriptButton"
        static let copyTranscriptButton = "recappi.cloud.copyTranscriptButton"
        static let openRecordingInBrowserButton = "recappi.cloud.openRecordingInBrowserButton"
        static let retranscribeButton = "recappi.cloud.retranscribeButton"
        static let confirmRetranscribeButton = "recappi.cloud.confirmRetranscribeButton"
        static let revealLocalSessionButton = "recappi.cloud.revealLocalSessionButton"
        static let downloadAudioButton = "recappi.cloud.downloadAudioButton"
        static let deleteButton = "recappi.cloud.deleteButton"
        static let confirmDeleteButton = "recappi.cloud.confirmDeleteButton"
    }
}
